"""PlatformIO pre-build script: gzip ../web into src/generated/web_assets.h.

The web app ships inside the firmware image, so one flash updates everything
and the user's settings/recipes on LittleFS are never overwritten.
"""

import gzip
import pathlib

Import("env")  # noqa: F821  (provided by PlatformIO/SCons)

PROJECT = pathlib.Path(env["PROJECT_DIR"])  # noqa: F821
WEB = (PROJECT / ".." / "web").resolve()
OUT = PROJECT / "src" / "generated" / "web_assets.h"

MIME = {
    ".html": "text/html",
    ".js": "text/javascript",
    ".css": "text/css",
    ".json": "application/json",
    ".webmanifest": "application/manifest+json",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".ico": "image/x-icon",
}


def c_bytes(data: bytes) -> str:
    rows = []
    for i in range(0, len(data), 20):
        rows.append("  " + ",".join(f"0x{b:02x}" for b in data[i : i + 20]))
    return ",\n".join(rows)


def generate() -> str:
    files = sorted(p for p in WEB.rglob("*") if p.is_file() and p.suffix in MIME)
    parts = [
        "// Generated by scripts/embed_web.py from web/. Do not edit.",
        "#pragma once",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "struct WebAsset {",
        "  const char* path;",
        "  const char* mime;",
        "  const uint8_t* data;",
        "  size_t len;",
        "};",
        "",
    ]
    table = []
    for i, path in enumerate(files):
        data = gzip.compress(path.read_bytes(), compresslevel=9, mtime=0)
        url = "/" + path.relative_to(WEB).as_posix()
        parts.append(f"// {url}")
        parts.append(f"static const uint8_t kAsset{i}[] = {{\n{c_bytes(data)}\n}};")
        table.append(f'  {{"{url}", "{MIME[path.suffix]}", kAsset{i}, {len(data)}}},')

    parts.append("static const WebAsset kWebAssets[] = {")
    parts.extend(table)
    parts.append("};")
    parts.append(f"static const size_t kWebAssetCount = {len(files)};")

    defaults = (WEB / "default-recipes.json").read_bytes() + b"\0"
    parts.append("")
    parts.append(f"static const char kDefaultRecipesJson[] = {{\n{c_bytes(defaults)}\n}};")
    return "\n".join(parts) + "\n"


content = generate()
OUT.parent.mkdir(parents=True, exist_ok=True)
if not OUT.exists() or OUT.read_text() != content:
    OUT.write_text(content)
    print(f"embed_web: wrote {OUT.relative_to(PROJECT)}")
